### ISSUE TITLE
Error display when there are two labels

### ISSUE THREAD

**Issue by xiyaowong** [yelog/vim-flash#30]
# Problem

GIF

![flash](https://github.com/user-attachments/assets/4e9e6043-8264-4820-ba09-e40d5f057bb1)

# Expected Behavior

When there are two labels, after pressing the first label, the first label should be hidden, and the second label should be shown.

**Comment by yelog** [comment]
It seems that there is something wrong with the background color of the second letter.

Thanks for your report. Will be fixed in the next version

**Comment by yelog** [comment]
The latest version has already fixed the issue. Please upgrade to version 0.0.4 and try again.

![2024-09-27 09 39 21](https://github.com/user-attachments/assets/9bf661de-db8a-4007-9342-b2f0687f9b1c)

**Comment by xiyaowong** [comment]
Confirmed :+1:
